### ISSUE TITLE
Strange fix needed for NixOS

### ISSUE THREAD

**Issue by laMudri** [mike-fabian/ibus-table#8]
I've been trying to fix issues with the `ibus-table` package for NixOS after the recent update (1.9.21). One is that changing to a table-based IM fails, printing this to `~/.cache/ibus-table/debug.log`:

```
Compatible database /home/james/.local/share/ibus-table/tables/ipa-x-sampa-user.db found.
Connect to the database /home/james/.local/share/ibus-table/tables/ipa-x-sampa-user.db.
failed to create engine ipa-x-sampa
Traceback (most recent call last):
  File "/nix/store/2rnlpn71v7mds7qfn9nk40csj913v38s-ibus-table-1.9.21/share/ibus-table/engine/factory.py", line 84, in do_create_engine
    self.dbdict[engine_name])
  File "/nix/store/2rnlpn71v7mds7qfn9nk40csj913v38s-ibus-table-1.9.21/share/ibus-table/engine/table.py", line 1545, in __init__
    self.db)
  File "/nix/store/2rnlpn71v7mds7qfn9nk40csj913v38s-ibus-table-1.9.21/share/ibus-table/engine/table.py", line 358, in __init__
    orientation=self._orientation)
  File "/nix/store/2rnlpn71v7mds7qfn9nk40csj913v38s-ibus-table-1.9.21/share/ibus-table/engine/table.py", line 410, in get_new_lookup_table
    round=True)
TypeError: gobject `IBusLookupTable' doesn't support property `page_size'
Traceback (most recent call last):
  File "/nix/store/2rnlpn71v7mds7qfn9nk40csj913v38s-ibus-table-1.9.21/share/ibus-table/engine/factory.py", line 84, in do_create_engine
    self.dbdict[engine_name])
  File "/nix/store/2rnlpn71v7mds7qfn9nk40csj913v38s-ibus-table-1.9.21/share/ibus-table/engine/table.py", line 1545, in __init__
    self.db)
  File "/nix/store/2rnlpn71v7mds7qfn9nk40csj913v38s-ibus-table-1.9.21/share/ibus-table/engine/table.py", line 358, in __init__
    orientation=self._orientation)
  File "/nix/store/2rnlpn71v7mds7qfn9nk40csj913v38s-ibus-table-1.9.21/share/ibus-table/engine/table.py", line 410, in get_new_lookup_table
    round=True)
TypeError: gobject `IBusLookupTable' doesn't support property `page_size'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/nix/store/2rnlpn71v7mds7qfn9nk40csj913v38s-ibus-table-1.9.21/share/ibus-table/engine/factory.py", line 92, in do_create_engine
    raise Exception("Cannot create engine %s from %s" % (engine_name, db_dir))
Exception: Cannot create engine ipa-x-sampa from /nix/store/1mvij9fb4nppjc2cfwfkklp33qsnhkx9-ibus-with-plugins-1.5.20/share/ibus-table/tables
```

(Ignore the slight difference from usual in the last `raise Exception` line. I added a little bit for debugging.)

A fix to this appears to be to edit [this line](https://github.com/mike-fabian/ibus-table/blob/7bf7a90d189364678a53aad1149246b5bff3a2e8/engine/table.py#L406-L410) so that it calls `IBus.LookupTable.new` rather than `IBus.LookupTable`. This is what `ibus-anthy` does.

This fix seems to work perfectly well, but it makes me surprised that `ibus-table` isn't broken on other systems. I would prefer to understand what's going on, too. For example, [LookupTable.py](https://github.com/ibus/ibus/blob/master/ibus/lookuptable.py) doesn't have a `new` method, so it surprises me that this works.

Some more details may be found in [this issue thread](https://github.com/NixOS/nixpkgs/issues/56621) (not all relevant).

**Comment by jtojnar** [comment]
LookupTable.py is from Python 2 bindings, ibus-table uses `gobject-introspection`-generated bindings:

https://lazka.github.io/pgi-docs/IBus-1.0/classes/LookupTable.html#IBus.LookupTable

**Comment by laMudri** [comment]
Fixed downstream (https://github.com/NixOS/nixpkgs/pull/61978).
